#! /bin/sh

# Define startup applications
sxhkd &
wal -i $HOME/Pictures/purseowner.png -n &
feh --bg-fill $HOME/Pictures/wp.png &
picom --config $HOME/.config/picom.conf &
sh $HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding		5
bspc config bottom_padding	20
bspc config left_padding	5
bspc config right_padding	5

bspc config focus_follows_pointer true

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
